services:
  backend:
    container_name: backend
    build: ./backend
    ports:
      - "8000:8000"
    depends_on:
      - db

  db:
    container_name: db
    restart: always
    image: postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"

  frontend:
    container_name: frontend
    build: ./frontend
    ports:
      - "3000:3000"
